// export const ZIPCODE_REQUEST = 'ZIPCODE_REQUEST'
// export const ZIPCODE_SUCCESS = 'ZIPCODE_SUCCESS'
// export const ZIPCODE_FAILURE = 'ZIPCODE_FAILURE'

export const RECEIVE_RESTAURANTS = 'RECEIVE_RESTAURANTS'
export const CLEAR_RESTAURANTS = 'CLEAR_RESTAURANTS'

export const SELECT_RESTAURANT = 'SELECT_RESTAURANT'
