export const RECEIVE_RESTAURANTS = 'RECEIVE_RESTAURANTS'
export const CLEAR_RESTAURANTS = 'CLEAR_RESTAURANTS'
export const SELECT_RESTAURANT = 'SELECT_RESTAURANT'
export const RECEIVE_MENU = 'RECEIVE_MENU'

export const SET_OPTIONS = 'SET_OPTIONS'
