export const RECEIVE_RESTAURANTS = 'RECEIVE_RESTAURANTS'
export const CLEAR_RESTAURANTS = 'CLEAR_RESTAURANTS'
export const SELECT_RESTAURANT = 'SELECT_RESTAURANT'
export const RECEIVE_MENU = 'RECEIVE_MENU'

export const SET_OPTION_TOPPINGS = 'SET_TOPPINGS'
export const SET_OPTION_PEOPLE = 'SET_PEOPLE'
export const SET_OPTION_HUNGER = 'SET_HUNGER'

export const BUILD_PIZZA = 'BUILD_PIZZA'
export const BUILD_ORDER = 'BUILD_ORDER'
